apiVersion: apps/v1
kind: Deployment
metadata:
  name: dstone-ai-engine
  namespace: dstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstone-ai-engine
  template:
    metadata:
      labels:
        app: dstone-ai-engine
    spec:
      containers:
        - name: dstone-ai-engine
          image: localhost:5000/dstone-ai-engine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: conf
              mountPath: /app/dstone/dstone-ai-engine/conf
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: conf
          configMap:
            name: dstone-ai-engine-conf
