apiVersion: v1
kind: Service
metadata:
  name: dstone-ai-engine
  namespace: dstone
spec:
  type: NodePort
  selector:
    app: dstone-ai-engine
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082
