



DECLARE

	V_MCOMP_DATA_NUM NUMBER := 0;   
	V_MSG VARCHAR2(2000) := '';   
	
	V_BICD_ROW AL_BICD_INFO%ROWTYPE;
	V_MCOMP_ROW AL_MCOMP_INFO%ROWTYPE;
	V_EVALOPN_ROW AL_ALSTUDY_EVAL_OPN%ROWTYPE;
	
BEGIN
	-- 1. 荤诀厘包府
    DELETE FROM AL_BICD_INFO;
	FOR BI_CURSOR IN (
		SELECT DISTINCT
		    D.DETAILCD COMPCD, D.CDNM COMPNM, B.BICD, B.BINM
		FROM
		    SYS_CD_DETAIL D,
		    (
			SELECT 
			--*
			DISTINCT OUCOMPCD, CURBICD BICD, CURBINM BINM
			FROM AL_HR_BASIC 
			--WHERE CURBICD IS NOT NULL
		    ) B
		WHERE 1=1
		    AND D.DETAILCD = B.OUCOMPCD
		    AND D.COMPCD = 'A10'
		    AND D.GRPCD = 'AL001'
		    --AND B.BICD IS NOT NULL
		    AND USEBEGINDT <=TO_CHAR(SYSDATE, 'YYYYMMDD') AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= DISUSEDT    
	) LOOP
	
		V_BICD_ROW.COMPCD := BI_CURSOR.COMPCD ;
		V_BICD_ROW.BICD := BI_CURSOR.BICD;
		V_BICD_ROW.BINM := BI_CURSOR.BINM;
		V_BICD_ROW.USEYN := 'Y';
		V_BICD_ROW.INPUTID := 'SYSTEM';
		V_BICD_ROW.INPUTDT := SYSDATE;
				
	    BEGIN			
    		INSERT INTO AL_BICD_INFO  
    		 ( 
    		    COMPCD , BICD , BINM , USEYN , INPUTID ,
    		    INPUTDT , UPDATEID , UPDATEDT  
    		 ) 
    		VALUES 
    		 ( 
    		    V_BICD_ROW.COMPCD , V_BICD_ROW.BICD , V_BICD_ROW.BINM , V_BICD_ROW.USEYN , V_BICD_ROW.INPUTID ,
    		    V_BICD_ROW.INPUTDT , V_BICD_ROW.UPDATEID , V_BICD_ROW.UPDATEDT  
    		 ) ;
           
    	EXCEPTION WHEN OTHERS THEN
			V_MSG:= SUBSTRB(SQLERRM,1,200);
			DBMS_OUTPUT.PUT_LINE(V_MSG);    		
    	END;		 
				
	END LOOP;
	
	-- 2. 林包贸包府
    DELETE FROM AL_MCOMP_INFO;
	FOR MCOMP_CURSOR IN (
		WITH COMPCD AS(
		    SELECT 
		        DETAILCD, CDNM
		    FROM 
		        SYS_CD_DETAIL 
		    WHERE 1=1
		        AND COMPCD = 'A10'        					-- 颇扼皋磐 (包府雀荤内靛)	
		        AND GRPCD  = 'AL001'           
		        AND TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN USEBEGINDT AND DISUSEDT
		)         
		SELECT
		    COMPCD  , CDNM COMPNM, BICD  , BINM  , USEYN  , INPUTID  ,
    		INPUTDT  , UPDATEID  , UPDATEDT
		FROM
			AL_BICD_INFO B, COMPCD C
        WHERE
            B.COMPCD = C.DETAILCD
	) LOOP
		V_MCOMP_ROW.MCOMPID	:= MCOMP_CURSOR.COMPCD||':'||MCOMP_CURSOR.BICD;
		V_MCOMP_ROW.COMPCD	:= MCOMP_CURSOR.COMPCD;
		V_MCOMP_ROW.BICD	:= MCOMP_CURSOR.BICD;
		IF V_MCOMP_ROW.COMPCD = V_MCOMP_ROW.BICD THEN
		  V_MCOMP_ROW.MCOMPNM	:= MCOMP_CURSOR.COMPNM;
		ELSE
		  V_MCOMP_ROW.MCOMPNM	:= MCOMP_CURSOR.COMPNM||' '||MCOMP_CURSOR.BINM;
		END IF;		
		V_MCOMP_ROW.INPUTID	:= 'SYSTEM';
		V_MCOMP_ROW.INPUTDT := SYSDATE;	
		
		INSERT INTO AL_MCOMP_INFO  
		 ( 
		    MCOMPID , COMPCD , BICD , MCOMPNM , INPUTID ,
		    INPUTDT , UPDATEID , UPDATEDT  
		 ) 
		VALUES 
		 ( 
		    V_MCOMP_ROW.MCOMPID , V_MCOMP_ROW.COMPCD , V_MCOMP_ROW.BICD , V_MCOMP_ROW.MCOMPNM , V_MCOMP_ROW.INPUTID ,
		    V_MCOMP_ROW.INPUTDT , V_MCOMP_ROW.UPDATEID , V_MCOMP_ROW.UPDATEDT  
		 ) ;
		 V_MCOMP_DATA_NUM := V_MCOMP_DATA_NUM +1;
	END LOOP;
			
	COMMIT;
	    
END;





