

DECLARE

	V_MSG VARCHAR2(2000) := '';   

	V_ATTC_FILE_ROW 	AL_ATTC_FILE%ROWTYPE;	
	V_ATTC_ROW 			AL_ATTC%ROWTYPE;	
		
	V_CEO_APPR_ROW 		AL_CEO_APPR%ROWTYPE;	
	V_MID_REPO_ROW 		AL_MID_REPO%ROWTYPE;	
	V_LST_REPO_ROW 		AL_LST_REPO%ROWTYPE;	
	
BEGIN
	-- 1. CEO 결재상신
    DELETE FROM AL_CEO_APPR;
	FOR TASK_CURSOR IN (
	    SELECT 
	        *
	    FROM AL_TASK_INFO
	    WHERE 1=1
	    	AND COMPCD = 'A10'
	    	AND CRSCD = 'A10B00001'
	    	AND CRSNO = '16'
	) LOOP

		-- * 첨부
		V_ATTC_ROW.ATTCID		:=LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		V_ATTC_ROW.INPUTID		:= 'SYSTEM';
		V_ATTC_ROW.INPUTDT		:= SYSDATE-30;
		INSERT INTO AL_ATTC  
		 ( 
		    ATTCID , INPUTID , INPUTDT , UPDATEID , UPDATEDT 
		 ) 
		VALUES 
		 ( 
		    V_ATTC_ROW.ATTCID , V_ATTC_ROW.INPUTID , V_ATTC_ROW.INPUTDT , V_ATTC_ROW.UPDATEID , V_ATTC_ROW.UPDATEDT 
		 );	
		-- * 첨부파일	
		V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
		V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
        --10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
		V_ATTC_FILE_ROW.ATTCKD			:= '10';
		V_ATTC_FILE_ROW.SAVEPATH		:= '/CIC/ALC/REPO/Disk34/CEO/'||V_ATTC_FILE_ROW.FILEID||'.txt';
		V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||'CEO결재상신첨부자료.txt';
		V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
		INSERT INTO AL_ATTC_FILE  
		 ( 
		    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
		    SAVEFILENM  
		 ) 
		VALUES 
		 ( 
		    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
		    V_ATTC_FILE_ROW.SAVEFILENM   
		 );
		 		
		-- 1-1. ROW 값 채우기
		V_CEO_APPR_ROW.COMPCD	:= TASK_CURSOR.COMPCD;
		V_CEO_APPR_ROW.CRSCD 	:= TASK_CURSOR.CRSCD;
		V_CEO_APPR_ROW.CRSNO	:= TASK_CURSOR.CRSNO;
		V_CEO_APPR_ROW.TEAMID	:= TASK_CURSOR.TEAMID;
		V_CEO_APPR_ROW.MISKEY	:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		V_CEO_APPR_ROW.CONTS	:= '1. 선정배경(전략적 중요성) \n..... \n2. 기대효과(과제해결 후 경영성과) \n..... \n3. 수행프로세스 및 방법 \n..... \n';
		-- 1-1-1. (1:결재진행중, 2:완결, 3:반려, 4:상신취소, 5:전결, 6:후완결)
		V_CEO_APPR_ROW.PROCSTAT := TO_CHAR(ROUND(MOD(DBMS_RANDOM.VALUE*10, 7)));
		V_CEO_APPR_ROW.ATTCID	:= V_ATTC_ROW.ATTCID;
		V_CEO_APPR_ROW.INPUTID	:= 'SYSTEM';
		V_CEO_APPR_ROW.INPUTDT	:= V_ATTC_ROW.INPUTDT;		
		-- 1-2. 입력 SQL
		INSERT INTO AL_CEO_APPR  
		 ( 
		    COMPCD , CRSCD , CRSNO , TEAMID , MISKEY , CONTS, 
		    PROCSTAT , ATTCID , INPUTID , INPUTDT , UPDATEID ,
		    UPDATEDT  
		 ) 
		VALUES 
		 ( 
		    V_CEO_APPR_ROW.COMPCD , V_CEO_APPR_ROW.CRSCD , V_CEO_APPR_ROW.CRSNO , V_CEO_APPR_ROW.TEAMID , V_CEO_APPR_ROW.MISKEY , V_CEO_APPR_ROW.CONTS ,
		    V_CEO_APPR_ROW.PROCSTAT , V_CEO_APPR_ROW.ATTCID , V_CEO_APPR_ROW.INPUTID , V_CEO_APPR_ROW.INPUTDT , V_CEO_APPR_ROW.UPDATEID ,
		    V_CEO_APPR_ROW.UPDATEDT 
		 );		 
						
	END LOOP;
	
	-- 2. 중간보고
    DELETE FROM AL_MID_REPO;
	FOR TASK_CURSOR IN (
	    SELECT 
	        *
	    FROM AL_TASK_INFO
	    WHERE 1=1
	    	AND COMPCD = 'A10'
	    	AND CRSCD = 'A10B00001'
	    	AND CRSNO = '16'
	) LOOP
	
		FOR I IN 0..(5-1) LOOP
			-- * 첨부
			V_ATTC_ROW.ATTCID		:=LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
			V_ATTC_ROW.INPUTID		:= 'SYSTEM';
			V_ATTC_ROW.INPUTDT		:= SYSDATE-20-(5-I);
			INSERT INTO AL_ATTC  
			 ( 
			    ATTCID , INPUTID , INPUTDT , UPDATEID , UPDATEDT 
			 ) 
			VALUES 
			 ( 
			    V_ATTC_ROW.ATTCID , V_ATTC_ROW.INPUTID , V_ATTC_ROW.INPUTDT , V_ATTC_ROW.UPDATEID , V_ATTC_ROW.UPDATEDT 
			 );	
			-- * 첨부파일1
			V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
			V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
            --10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
			V_ATTC_FILE_ROW.ATTCKD			:= '20';
			V_ATTC_FILE_ROW.SAVEPATH		:= '/CIC/ALC/REPO/Disk34/MIDREPO/'||V_ATTC_FILE_ROW.FILEID||'.txt';
			V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||' '||I||'번째 중간보고 첨부자료1.txt';
			V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
			INSERT INTO AL_ATTC_FILE  
			 ( 
			    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
			    SAVEFILENM  
			 ) 
			VALUES 
			 ( 
			    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
			    V_ATTC_FILE_ROW.SAVEFILENM   
			 );
			-- * 첨부파일2
			V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
			V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
			V_ATTC_FILE_ROW.ATTCKD			:= '20';
			V_ATTC_FILE_ROW.SAVEPATH		:= '/CIC/ALC/REPO/Disk34/MIDREPO/'||V_ATTC_FILE_ROW.FILEID||'.txt';
			V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||' '||I||'번째중간보고 첨부자료2.txt';
			V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
			INSERT INTO AL_ATTC_FILE  
			 ( 
			    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
			    SAVEFILENM  
			 ) 
			VALUES 
			 ( 
			    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
			    V_ATTC_FILE_ROW.SAVEFILENM   
			 );		 
			 	
			-- 2-1. ROW 값 채우기
			V_MID_REPO_ROW.COMPCD		:= TASK_CURSOR.COMPCD;
			V_MID_REPO_ROW.CRSCD 		:= TASK_CURSOR.CRSCD;
			V_MID_REPO_ROW.CRSNO		:= TASK_CURSOR.CRSNO;
			V_MID_REPO_ROW.TEAMID		:= TASK_CURSOR.TEAMID;
		    V_MID_REPO_ROW.SEQ 			:= I;
		    V_MID_REPO_ROW.MIDREPONM 	:= TASK_CURSOR.TEAMID||' '||I||'번째 중간보고';
		    V_MID_REPO_ROW.MIDREPODT 	:= TO_CHAR(SYSDATE+20, 'YYYYMMDD');
		    V_MID_REPO_ROW.CONTS 		:= TASK_CURSOR.TEAMID||' '||I||'번째 중간보고 내용 ..........';
		    V_MID_REPO_ROW.FEEDBACK 	:= TASK_CURSOR.TEAMID||' '||I||'번째 중간보고 피드백 ..........';
		    V_MID_REPO_ROW.INPUTID		:= 'SYSTEM';
		    V_MID_REPO_ROW.INPUTDT 		:= V_ATTC_ROW.INPUTDT;
		    V_MID_REPO_ROW.ATTCID 		:= V_ATTC_ROW.ATTCID;	
			-- 2-2. 입력 SQL
			INSERT INTO AL_MID_REPO  
			 ( 
			    COMPCD , CRSCD , CRSNO , TEAMID , SEQ ,
			    MIDREPONM , MIDREPODT , CONTS , FEEDBACK , INPUTID ,
			    INPUTDT , UPDATEID , UPDATEDT , ATTCID  
			 ) 
			VALUES 
			 ( 
			    V_MID_REPO_ROW.COMPCD , V_MID_REPO_ROW.CRSCD , V_MID_REPO_ROW.CRSNO , V_MID_REPO_ROW.TEAMID , V_MID_REPO_ROW.SEQ ,
			    V_MID_REPO_ROW.MIDREPONM , V_MID_REPO_ROW.MIDREPODT , V_MID_REPO_ROW.CONTS , V_MID_REPO_ROW.FEEDBACK , V_MID_REPO_ROW.INPUTID ,
			    V_MID_REPO_ROW.INPUTDT , V_MID_REPO_ROW.UPDATEID , V_MID_REPO_ROW.UPDATEDT , V_MID_REPO_ROW.ATTCID 
			 );
		 END LOOP;	
	END LOOP;
	
	-- 3. 최종보고
    DELETE FROM AL_LST_REPO;
	FOR TASK_CURSOR IN (
	    SELECT 
	        *
	    FROM AL_TASK_INFO
	    WHERE 1=1
	    	AND COMPCD = 'A10'
	    	AND CRSCD = 'A10B00001'
	    	AND CRSNO = '16'
	) LOOP

		-- * 첨부
		V_ATTC_ROW.ATTCID		:=LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		V_ATTC_ROW.INPUTID		:= 'SYSTEM';
		V_ATTC_ROW.INPUTDT		:= SYSDATE-10;
		INSERT INTO AL_ATTC  
		 ( 
		    ATTCID , INPUTID , INPUTDT , UPDATEID , UPDATEDT 
		 ) 
		VALUES 
		 ( 
		    V_ATTC_ROW.ATTCID , V_ATTC_ROW.INPUTID , V_ATTC_ROW.INPUTDT , V_ATTC_ROW.UPDATEID , V_ATTC_ROW.UPDATEDT 
		 );	
		-- * 첨부파일(최종보고서 변환)
		V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
		V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		--10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
		V_ATTC_FILE_ROW.ATTCKD			:= '30';
		V_ATTC_FILE_ROW.SAVEPATH		:= 'CIC/ALC/REPORT/Disk32/'||V_ATTC_FILE_ROW.FILEID||'.zip';
		V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||'최종보고서첨부자료.zip';
		V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
		INSERT INTO AL_ATTC_FILE  
		 ( 
		    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
		    SAVEFILENM , ATTCINFO
		 ) 
		VALUES 
		 ( 
		    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
		    V_ATTC_FILE_ROW.SAVEFILENM ,   V_ATTC_FILE_ROW.ATTCINFO
		 );
		-- * 첨부파일(최종보고서 원본)
		V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
		V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		--10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
		V_ATTC_FILE_ROW.ATTCKD			:= '31';
		V_ATTC_FILE_ROW.SAVEPATH		:= 'CIC/ALC/REPORT/Disk32/'||V_ATTC_FILE_ROW.FILEID||'.txt';
		V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||'최종보고서첨부자료.txt';
		V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
		INSERT INTO AL_ATTC_FILE  
		 ( 
		    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
		    SAVEFILENM  , ATTCINFO
		 ) 
		VALUES 
		 ( 
		    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
		    V_ATTC_FILE_ROW.SAVEFILENM  ,   V_ATTC_FILE_ROW.ATTCINFO 
		 );
		-- * 첨부파일(최종발표자료 변환)	
		V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
		V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		--10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
		V_ATTC_FILE_ROW.ATTCKD			:= '32';
		V_ATTC_FILE_ROW.SAVEPATH		:= '/CIC/ALC/REPORT/Disk32/'||V_ATTC_FILE_ROW.FILEID||'.txt';
		V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||'최종발표자료첨부자료.txt';
		V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
		INSERT INTO AL_ATTC_FILE  
		 ( 
		    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
		    SAVEFILENM  , ATTCINFO
		 ) 
		VALUES 
		 ( 
		    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
		    V_ATTC_FILE_ROW.SAVEFILENM ,   V_ATTC_FILE_ROW.ATTCINFO  
		 );	
		-- * 첨부파일(최종발표자료 원본)	
		V_ATTC_FILE_ROW.ATTCID			:= V_ATTC_ROW.ATTCID;
		V_ATTC_FILE_ROW.FILEID			:= LPAD( TO_CHAR(ROUND(DBMS_RANDOM.VALUE*10000000000000000000000000000000)), 32, '0' );
		--10:CEO결재상신, 20:중간보고, 30:AL자료(최종보고서 변환), 31:AL자료(최종보고서 원본), 32:AL자료(최종발표자료 변환), 33:AL자료(최종발표자료 원본), 40:팀공유자료	
		V_ATTC_FILE_ROW.ATTCKD			:= '33';
		V_ATTC_FILE_ROW.SAVEPATH		:= '/CIC/ALC/REPORT/Disk32/'||V_ATTC_FILE_ROW.FILEID||'.txt';
		V_ATTC_FILE_ROW.ORIFILENM		:= TASK_CURSOR.TEAMID||'최종발표자료첨부자료.txt';
		V_ATTC_FILE_ROW.ATTCINFO        := V_ATTC_FILE_ROW.FILEID||'*'||V_ATTC_FILE_ROW.ORIFILENM||'*'||'파일형식명'||'*'||'/CIC/TEMP/ALC/Disk31/tmp/'||V_ATTC_FILE_ROW.FILEID||'*'||879394;
		INSERT INTO AL_ATTC_FILE  
		 ( 
		    ATTCID , FILEID , ATTCKD , SAVEPATH , ORIFILENM ,
		    SAVEFILENM  , ATTCINFO
		 ) 
		VALUES 
		 ( 
		    V_ATTC_FILE_ROW.ATTCID , V_ATTC_FILE_ROW.FILEID , V_ATTC_FILE_ROW.ATTCKD , V_ATTC_FILE_ROW.SAVEPATH , V_ATTC_FILE_ROW.ORIFILENM ,
		    V_ATTC_FILE_ROW.SAVEFILENM ,   V_ATTC_FILE_ROW.ATTCINFO  
		 );		 	 
		 
		-- 3-1. ROW 값 채우기
		V_LST_REPO_ROW.COMPCD		:= TASK_CURSOR.COMPCD;
		V_LST_REPO_ROW.CRSCD 		:= TASK_CURSOR.CRSCD;
		V_LST_REPO_ROW.CRSNO		:= TASK_CURSOR.CRSNO;
		V_LST_REPO_ROW.TEAMID		:= TASK_CURSOR.TEAMID;
		V_LST_REPO_ROW.INPUTID		:= 'SYSTEM';
		V_LST_REPO_ROW.INPUTDT 		:= V_ATTC_ROW.INPUTDT;
		V_LST_REPO_ROW.ATTCID 		:= V_ATTC_ROW.ATTCID;
		 
		-- 3-2. 입력 SQL
		INSERT INTO AL_LST_REPO  
		 ( 
		    COMPCD , CRSCD , CRSNO , TEAMID , INPUTID ,
		    INPUTDT , UPDATEID , UPDATEDT , ATTCID  
		 ) 
		VALUES 
		 ( 
		    V_LST_REPO_ROW.COMPCD , V_LST_REPO_ROW.CRSCD , V_LST_REPO_ROW.CRSNO , V_LST_REPO_ROW.TEAMID , V_LST_REPO_ROW.INPUTID ,
		    V_LST_REPO_ROW.INPUTDT , V_LST_REPO_ROW.UPDATEID , V_LST_REPO_ROW.UPDATEDT , V_LST_REPO_ROW.ATTCID  
		 );		
	END LOOP;
	
	COMMIT;
	    
END;




