/**********************************************
Sample 데이터베이스[Application용] 테이블
**********************************************/

USE sampleDB;

CREATE TABLE IF NOT EXISTS SAMPLE_MEMBER (
  GROUP_ID VARCHAR(30) NOT NULL, 
  USER_ID VARCHAR(30) NOT NULL, 
  USER_PW VARCHAR(30) ,   
  MEMBER_NAME VARCHAR(40) NOT NULL,   
  AGE VARCHAR(12) ,   
  DUTY VARCHAR(40) ,     
  REGION VARCHAR(100) , 
  ADDRESS VARCHAR(255) , 
  ADDRESS_DTL VARCHAR(255) ,  
  JUMINNO VARCHAR(13) ,    
  GENDER VARCHAR(2) ,    
  TEL VARCHAR(15) ,    
  HP VARCHAR(15) ,    
  EMAIL VARCHAR(150) ,   
  INPUT_DT DATE NOT NULL,  
  UPDATE_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID, USER_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP (
  GROUP_ID VARCHAR(30) NOT NULL, 
  GROUP_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE (
  ROLE_ID VARCHAR(30) NOT NULL, 
  ROLE_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP_ROLE (
  GROUP_ID VARCHAR(30) NOT NULL, 
  ROLE_ID VARCHAR(30) NOT NULL, 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID, ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE_PROG (
  ROLE_ID VARCHAR(30) NOT NULL, 
  PROG_ID VARCHAR(30) NOT NULL, 
  PROG_NAME VARCHAR(200), 
  PROG_URL VARCHAR(200), 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID, PROG_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_TEST (
  TEST_ID BIGINT NOT NULL AUTO_INCREMENT,
  TEST_NAME VARCHAR(200), 
  FLAG_YN VARCHAR(1), 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (TEST_ID)
) ;

/**********************************************
사가(Saga)+아웃박스 패턴용 테이블
**********************************************/
CREATE TABLE IF NOT EXISTS TB_SAGA_INSTANCE (
  SAGA_ID       VARCHAR(64)   NOT NULL,
  SAGA_TYPE     VARCHAR(100)  NOT NULL,
  STATUS        VARCHAR(20)   NOT NULL,
  CURRENT_STEP  VARCHAR(100),
  CREATED_DT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_DT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (SAGA_ID)
) ;
CREATE TABLE IF NOT EXISTS TB_SAGA_STEP_HISTORY (
  ID          BIGINT        NOT NULL AUTO_INCREMENT,
  SAGA_ID     VARCHAR(64)   NOT NULL,
  STEP_NAME   VARCHAR(100)  NOT NULL,
  RESULT      VARCHAR(20)   NOT NULL,
  ERROR_MSG   VARCHAR(1000),
  CREATED_DT  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IX_SAGA_STEP_SAGA_ID (SAGA_ID)
) ;
CREATE TABLE IF NOT EXISTS TB_OUTBOX_MESSAGE (
  ID          BIGINT        NOT NULL AUTO_INCREMENT,
  TOPIC       VARCHAR(200)  NOT NULL,
  MSG_KEY     VARCHAR(200),
  PAYLOAD     TEXT          NOT NULL,
  STATUS      VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
  RETRY_CNT   INT           NOT NULL DEFAULT 0,
  ERROR_MSG   VARCHAR(1000),
  CREATED_DT  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SENT_DT     DATETIME,
  PRIMARY KEY (ID),
  KEY IX_OUTBOX_STATUS (STATUS, ID)
) ;

