/**********************************************
Sample 데이터베이스[Application용] 테이블
**********************************************/

USE sampleDB;

CREATE TABLE IF NOT EXISTS SAMPLE_MEMBER (
  GROUP_ID VARCHAR(30) NOT NULL, 
  USER_ID VARCHAR(30) NOT NULL, 
  USER_PW VARCHAR(30) ,   
  MEMBER_NAME VARCHAR(40) NOT NULL,   
  AGE VARCHAR(12) ,   
  DUTY VARCHAR(40) ,     
  REGION VARCHAR(100) , 
  ADDRESS VARCHAR(255) , 
  ADDRESS_DTL VARCHAR(255) ,  
  JUMINNO VARCHAR(13) ,    
  GENDER VARCHAR(2) ,    
  TEL VARCHAR(15) ,    
  HP VARCHAR(15) ,    
  EMAIL VARCHAR(150) ,   
  INPUT_DT DATE NOT NULL,
  UPDATE_DT DATE NOT NULL,
  PRIMARY KEY  (GROUP_ID, USER_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP (
  GROUP_ID VARCHAR(30) NOT NULL, 
  GROUP_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE (
  ROLE_ID VARCHAR(30) NOT NULL, 
  ROLE_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP_ROLE (
  GROUP_ID VARCHAR(30) NOT NULL, 
  ROLE_ID VARCHAR(30) NOT NULL, 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID, ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE_PROG (
  ROLE_ID VARCHAR(30) NOT NULL, 
  PROG_ID VARCHAR(30) NOT NULL, 
  PROG_NAME VARCHAR(200), 
  PROG_URL VARCHAR(200), 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID, PROG_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_TEST (
  TEST_ID BIGINT NOT NULL AUTO_INCREMENT,
  TEST_NAME VARCHAR(200), 
  FLAG_YN VARCHAR(1), 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (TEST_ID)
) ;

/**********************************************
사가(Saga)+아웃박스 패턴용 테이블
**********************************************/
CREATE TABLE IF NOT EXISTS TB_SAGA_INSTANCE (
  SAGA_ID       VARCHAR(64)   NOT NULL,
  SAGA_TYPE     VARCHAR(100)  NOT NULL,
  STATUS        VARCHAR(20)   NOT NULL,
  CURRENT_STEP  VARCHAR(100),
  CREATED_DT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_DT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (SAGA_ID)
) ;
CREATE TABLE IF NOT EXISTS TB_SAGA_STEP_HISTORY (
  ID                     BIGINT        NOT NULL AUTO_INCREMENT,
  SAGA_ID                VARCHAR(64)   NOT NULL,
  STEP_NAME              VARCHAR(100)  NOT NULL,
  RESULT                 VARCHAR(20)   NOT NULL,
  ERROR_MSG              VARCHAR(1000),
  PAYLOAD                TEXT,
  COMPENSATE_RESULT      VARCHAR(20),
  COMPENSATE_ERROR_MSG   VARCHAR(1000),
  COMPENSATED_DT         DATETIME,
  CREATED_DT             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IX_SAGA_STEP_SAGA_ID (SAGA_ID),
  UNIQUE KEY UX_SAGA_STEP (SAGA_ID, STEP_NAME)
) ;
CREATE TABLE IF NOT EXISTS TB_OUTBOX_MESSAGE (
  ID              BIGINT        NOT NULL AUTO_INCREMENT,
  TOPIC           VARCHAR(200)  NOT NULL,
  MSG_KEY         VARCHAR(200),
  PAYLOAD         TEXT          NOT NULL,
  STATUS          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
  RETRY_CNT       INT           NOT NULL DEFAULT 0,
  ERROR_MSG       VARCHAR(1000),
  DISPATCH_TOKEN  VARCHAR(64),
  DISPATCHED_DT   DATETIME,
  CREATED_DT      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SENT_DT         DATETIME,
  PRIMARY KEY (ID),
  KEY IX_OUTBOX_STATUS (STATUS, ID),
  KEY IX_OUTBOX_DISPATCH (STATUS, DISPATCHED_DT)
) ;

/**********************************************
AI(dstone-ai-engine 연동) 관련 테이블
TB_AI_DOCUMENT는 dstone-ai-engine의 pgvector에 실제로 적재된 상태와는 별개로, dstone-boot 쪽에서
"무엇을 업로드했는지" 화면에 보여주기 위한 자체 메타데이터다. dstone-ai-engine의 RagController는
적재된 sourceId 목록을 조회하는 API가 없어(업로드/삭제/검색만 제공) 이 테이블로 대신한다.
**********************************************/

CREATE TABLE IF NOT EXISTS TB_AI_DOCUMENT (
  SOURCE_ID     VARCHAR(100)  NOT NULL,
  FILE_NAME     VARCHAR(255)  NOT NULL,
  CHUNK_COUNT   INT           NOT NULL DEFAULT 0,
  UPLOADER_ID   VARCHAR(30)   NOT NULL,
  INPUT_DT      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SOURCE_ID)
) ;
